version: '3.3'
services:

  coreserver:
    ports:
        - 3000:3000
        - "9229:9229"
    command:
        - node
        - "--inspect-brk=0.0.0.0"
        - "bin/www"
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
        - "8545:8545"
    entrypoint:
        - node
        - /app/ganache-core.docker.cli.js
        - -i
        - "28"
        - --deterministic
        - --mnemonic
        - "produce end reduce movie attend scan tone tag someone hour scout spoil"
        - --hostname
        - "0.0.0.0"
        - -l
        - "8000000"
