version: '3.3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ghost'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  # SECRET 
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - mysql
    environment:
      url: 'http://localhost:2368'
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: 'root'
      database__connection__database: ghost
    ports:
        - '2368:2368'
    expose:
        - '2368'
    volumes:
      - ghost_volume:/var/lib/ghost/content

  coreserver:
    image: coreserver:latest
    depends_on:
      - redis
      - db
    ports:
      - 3000:3000
    expose:
        - '3000'
    environment: 
      PGUSER: postgres
      PGPASSWORD: postgres
    command:
      - node
      - "bin/www"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.rebalancer.no-overlap: "true"
      ofelia.job-exec.rebalancer.schedule: "@every 10s"
      ofelia.job-exec.rebalancer.command: "node lib/rebalancer.js"

  eventProcessor:
    image: coreserver:latest
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
    command:
      - node
      - "lib/ethEventProcessor.js"

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - '6379:6379'
  
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - coreserver
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
volumes:
  my-db:
  postgres_data_volume:
  ghost_volume:
  redis_socket:
