version: '3.3'
services:

  commento:
    image: commento
    ports:
      - 8080:8080
    expose:
        - '8080'
    environment:
      COMMENTO_ORIGIN: http://localhost:8080
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
    depends_on:
      - db