version: '3.3'
services:

  coreserver:
    ports:
        - 3000:3000
        - "9229:9229"
    command:
        - node
        - "--inspect-brk=0.0.0.0"
        - "bin/www"

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
        - "8545:8545"
    entrypoint:
        - node
        - /app/ganache-core.docker.cli.js
        - -i
        - '28'
        - --hostname
        - '0.0.0.0'
        - "-l 8000000"
