version: '3.3'
services:
  commento:
    image: commento
    ports:
      - 8080:8080
    expose:
        - '8080'
    environment:
      COMMENTO_ORIGIN: http://localhost:8080
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network
  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ghost'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  ghost:
    image: ghost_or:latest
    restart: always
    depends_on:
      - mysql
    environment:
      url: 'http://127.0.0.1'
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: 'root'
      database__connection__database: ghost
    ports:
        - '2368:2368'
    expose:
        - '2368'
    volumes:
      - ghost_volume:/var/lib/ghost/content

  # metaauth:
  #   image: metaauth
  #   ports:
  #     - 3000:3000
  #   expose:
  #       - '3000'

networks:
  db_network:

volumes:
  my-db:
  postgres_data_volume:
  ghost_volume:
